name: rohit-project
services:
  - name: rohit-service
    environment_slug: python
    build_command: |
      chmod +x *
    run_command: chmod +x rohit
    python3 rohit.py
    http_port: 5000
    routes:
      - path: /
    envs:
      - key: TELEGRAM_BOT_TOKEN
        value: "7776000937:AAEyL8I91gGtiMh9dJNURD1DZgqs7Oy_3gw"
        scope: RUN_AND_BUILD
