name: rohit-project
services:
  - name: rohit-bot-service
    environment_slug: python
    build_command: |
      chmod +x build.sh && ./build.sh
    run_command: |
      gunicorn rohit:app --bind 0.0.0.0:5000
    http_port: 5000
    routes:
      - path: /
    envs:
      - key: TELEGRAM_BOT_TOKEN
        value: "your_bot_token_here"
        scope: RUN_AND_BUILD
    source_dir: /

