spec:
  name: rohit-bot-app
  services:
    - name: rohit-bot
      environment_slug: python
      instance_size_slug: basic-xxs
      instance_count: 1
      build_command: |
        pip install python-dotenv
        pip install -r requirements.txt
        chmod +x rohit
        pip install telebot pymongo aiohttp psutil
      run_command: |
         python3 rohit.py
        
      envs:
        - key: BOT_TOKEN
          value: '7776000937:AAGWS2CNiNV9hxRCr7WAANh0fzeovvKyLgA'

        - key: MONGO_DB_URL
          value: 'mongodb+srv://Bishal:Bishal@bishal.dffybpx.mongodb.net/?retryWrites=true&w=majority&appName=Bishal'
     
      http_port: 443
      timeout: 30
      delaytime: 6
      restart: 600
