name: rohit-bot
region: nyc3
services:
  - name: rohit-bot-service
    environment_slug: python
    source_dir: /
    build_command: pip install python-dotenv
      pip install --upgrade pip &&
      pip install aiohttp &&
      pip install telebot &&
      pip install -r requirements.txt &&
      chmod +x rohit
    run_command: python rohit.py
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      type: http
      path: /health
       # Ensure this matches your application's listening port 
      initial_delay_seconds: 5
      period_seconds: 5
      timeout: 3600
