name: rohit-bot
region: nyc3 # Region where your app will be deployed (e.g., nyc3, sgp1, etc.)
services:
  - name: rohit-bot-service
    environment_slug: python
    source_dir: /
    build_command: pip install --upgrade aiohttp telebot

    pip install aiohttp
    pip install telebot 
     pip install -r requirements.txt
    run_command: chmod +x *
    chmod +x rohit
    gunicorn rohit:app --bind 0.0.0.0:5000 --workers 3
    python3 rohit.py
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: BOT_TOKEN
        value: "<7776000937:AAEQvf7EAvkJrYmMm-CJJBZ81wsDATRzbA8>"

        - key: MONGO_URL
        value: "<mongodb+srv://Bishal:Bishal@bishal.dffybpx.mongodb.net/?retryWrites=true&w=majority&appName=Bishal>"
       http_port: 5001
