name: rohit-bot
region: nyc3
services:
  - name: rohit-bot-service
    environment_slug: python
    source_dir: /
    build_command: 
      pip install --upgrade pip &&
      pip install python-dotenv &&
      pip install aiohttp &&
      pip install telebot &&
      pip install -r requirements.txt &&
      chmod +x rohit
    run_command: python rohit.py
    instance_count: 1
    instance_size_slug: basic-xs  # Upgraded for better resources
      timeout: 30            # Increased timeout duration
