# digital.yml

# Bot and server configuration
bot:
  token: "7776000937:AAGWS2CNiNV9hxRCr7WAANh0fzeovvKyLgA"
  admin_id:
    - "5599402910"
  user_file: "users.txt"
  log_file: "log.txt"
  free_user_file: "free_users.txt"
  
server:
  host: "0.0.0.0"
  port: 5000

logs:
  max_size: 10MB
  max_age: 7d

# Build and Run Configuration
build:
  command: |
    pip install -r requirements.txt && chmod +x rohit
    # Add any other build-related commands here
    echo "Build complete."

run:
  command: |
    python rohit.py  # or your bot's entry point
    # Other run-related commands if needed
    echo "Bot is running!"

# Requirements File
requirements:
  - telebot==4.0.1
  - requests==2.28.1
  - datetime==4.7
  - flask==2.2.2  # If using Flask for keep-alive
  - subprocess
