name: rohit-project
services:
  - name: rohit-service
    environment_slug: python
    build_command: |
      chmod +x rohit
      pip install -r requirements.txt
    run_command: python3 rohit.py
    http_port: 5000
    routes:
      - path: /
    envs:
      - key: BOT_TOKEN
        value: "7776000937:AAFnSBFCnKvvu6nNTwlq_h7kBxNzHJHtFmQ"
        scope: RUN_AND_BUILD
