name: rohit-project
services:
  - name: rohit-service
    environment_slug: python
    build_command: |
      chmod +x build.sh && ./build.sh
    run_command: python3 rohit.py
    http_port: 5000
    routes:
      - path: /
    envs:
      - key: TELEGRAM_BOT_TOKEN
        value: "7776000937:AAHKMHSG3ufl65CUuVQ4ioxGijx1hBj9tqA"
        scope: RUN_AND_BUILD
