spec:
  name: rohit-bot-app
  services:
    - name: rohit-bot
      environment_slug: python
      instance_size_slug: basic-xxs
      instance_count: 1
      build_command: |
        pip install -r requirements.txt
        chmod +x rohit
        pip install telebot pymongo aiohttp psutil
      run_command: |
         python3 rohit.py
        
      envs:
        - key: BOT_TOKEN
          value: '7776000937:AAGWS2CNiNV9hxRCr7WAANh0fzeovvKyLgA'
      http_port: 5000
      timeout 15
      delaytime: 6
      restart: 600
