name: rohit-bot
region: nyc3
services:
  - name: rohit-bot-service
    environment_slug: python
    source_dir: /
    build_command: 
      pip install --upgrade pip &&
      pip install python-dotenv &&
      pip install aiohttp &&
      pip install telebot &&
      pip install -r requirements.txt &&
      chmod +x rohit
    run_command: python rohit.py
    instance_count: 1
    instance_size_slug: basic-xs  # Upgraded for better resources
    health_check:
      type: http
      path: /health
      initial_delay_seconds: 15  # Increased delay for application readiness
      period_seconds: 10         # Reduced frequency of checks
      timeout: 5                 # Increased timeout duration
