services:
  - type: web
    name: rohit-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && gcc -o rohit rohit.c"
    startCommand: "python rohit.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "7776000937:AAHKMHSG3ufl65CUuVQ4ioxGijx1hBj9tqA"
    ports:
      - 5000
