services:
  - type: web
    name: rohit-bot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      gcc -o rohit rohit.c
      chmod +x *
      chmod +x rohit  # Ensure rohit is executable
    startCommand: |
      ./rohit &  # Run 'rohit' in the background (optional if Python bot is primary)
      python rohit.py  # Run Telegram bot continuously
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "<7776000937:AAHKMHSG3ufl65CUuVQ4ioxGijx1hBj9tqA>"
    ports:
      - 5000
