version: 1

services:
  - type: web
    name: my-service
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: |
      chmod +x *
      chmod +x rohit
      pip install flask telebot pymongo aiohttp psutil gunicorn
    startCommand: gunicorn rohit:app --bind 0.0.0.0:8000
